{
 "title": "CPU",
 "tags": [
  "linux",
  "cpu"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,1h,6h,12h" },
   { "name": "step", "label": "step", "query": "30s,1m,5m,10m,1h,6h,12h" },
   {
    "name": "cpu",
    "label": "cpu",
    "query": "label_values(node_cpu_seconds_total, cpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$host\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$host\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$host\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(count(count by (cpu)(node_cpu_seconds_total{instance='$host'})))"
    }
   ]
  },
  {
   "title": "Average cpu %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_min((1 - avg(irate(node_cpu_seconds_total{instance=\"$host\", mode='idle'}[$interval])))*100, 0.0)"
    }
   ]
  },
  {
   "title": "Min frequency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "format": "hertz",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(node_cpu_frequency_min_hertz{instance='$host'})"
    }
   ]
  },
  {
   "title": "Max frequency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "format": "hertz",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(node_cpu_frequency_max_hertz{instance='$host'})"
    }
   ]
  },
  {
   "title": "Average frequency %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (avg(node_cpu_scaling_frequency_hertz{instance='$host'})-min(node_cpu_frequency_min_hertz{instance='$host'})) / (max(node_cpu_frequency_max_hertz{instance='$host'})-min(node_cpu_frequency_min_hertz{instance='$host'}))"
    }
   ]
  },
  {
   "title": "Throttles core",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_cpu_core_throttles_total{instance='$host'})"
    }
   ]
  },
  {
   "title": "Throttles package",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_cpu_package_throttles_total{instance='$host'})"
    }
   ]
  },
  {
   "title": "Throttles history",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_core_throttles_total{instance=\"$host\"}[$interval]))",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(irate(node_cpu_package_throttles_total{instance=\"$host\"}[$interval]))",
     "legendFormat": "Packages"
    }
   ]
  },
  {
   "title": "Average frequency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "hertz",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_cpu_scaling_frequency_hertz{instance='$host'})"
    }
   ]
  },
  { "title": "CPU $cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "cpu" },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='user', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='system', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='nice', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='idle', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='irq', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='softirq', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='iowait', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=\"$host\", mode='steal', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "node_cpu_frequency_max_hertz{instance='$host', cpu='$cpu'}",
     "legendFormat": "max"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance='$host', cpu='$cpu'}",
     "legendFormat": "current"
    },
    {
     "expr": "node_cpu_frequency_min_hertz{instance='$host', cpu='$cpu'}",
     "legendFormat": "min"
    }
   ]
  }
 ]
}